# FIXME mult-GPU / multi-transcribe worker
# FIXME cloud deploy? or remove? relevant https://github.com/aws/containers-roadmap/issues/327

version: '3.7'

networks:
    stack:
        driver: bridge

services:
    postgres:
        build:
            context: images/postgres
        container_name: postgres
        hostname: postgres
        user: postgres
        networks:
            - stack
        volumes:
            - ./data:/usr/src/app/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: always
        env_file: conf.env

    ingest:
        build:
            context: images/ingest
        container_name: ingest
        networks:
            - stack
        volumes:
            - ./data:/usr/src/app/data
        depends_on:
            - postgres
        environment:
            - POSTGRES_HOST=postgres
        restart: always
        env_file: conf.env

    transcribe:
        build:
            context: images/transcribe
        container_name: transcribe
        networks:
            - stack
        volumes:
            - ./data:/usr/src/app/data
        depends_on:
            - postgres
        environment:
            - POSTGRES_HOST=postgres
        restart: always
        env_file: conf.env
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
                          device_ids: ['1']
